# _config.yml

# site basic info
title: The Only Band in The World by Ryan Bird
author: 
description: >- # web description
  Read full text of The Only Band in The World by Ryan Bird.
url: "https://indilogic84.github.io" # site URL

# theme settings
#theme: jekyll-theme-minimal # this is an example
remote_theme: pages-themes/minimal@v0.2.0

# plugins (optional)
plugins:
  - jekyll-feed 
  - jekyll-remote-theme

collections:
  chapters:  # define a collection named "chapters"
    output: true # generate a seperate page for each of the chapters
    permalink: /chapters/:name/
